### ISSUE TITLE
Warning from SOCP example

### ISSUE THREAD

**Issue by kibaekkim** [Argonne-National-Laboratory/MaximinOPF.jl#24]
I have the following warning message from the socp model:
```
┌ Warning: MathOptInterface.VariablePrimalStart() is not supported by MathOptInterface.Bridges.Constraint.SingleBridgeOptimizer{MathOptInterface.Bridges.Constraint.QuadtoSOCBridge{Float64},MathOptInterface.Utilities.Model{Float64}}. This information will be discarded.
└ @ MathOptInterface.Utilities ~/.julia/packages/MathOptInterface/RmalA/src/Utilities/copy.jl:140
```
It may or may not be critical.

**Comment by bcdandurand** [comment]
My purpose of adding this bridge was so that QC-relaxed problems could be solved with, say, Mosek. But the bridge couldn't verify the QCs as convex (possible the functions defining them are quasiconvex). I'll remove the use of this bridge from the master branch at least, since it is not productive for supported usage, and for this reason, I'll close the issue.

As you say, it may or may not be critical. My guess is that the issue prevents the user from setting initial primal values. If I recall correctly, the bridges used by the Mosek.jl interface prevent such initialization also.
